### ISSUE TITLE
HELP WANTED : Configuring dhus 1.0 with an object storage datastore

### ISSUE THREAD

**Issue by mwabakangwa** [SentinelDataHub/dhus-distribution#2]
Im using ceph with swift api for my object storage. In configuring the datastore in dhus.xml, there are 3 apis to set for the provider, i set my provider to openstack-swift. But i noticed that in the logs there is a reference to openstack-keystone.  Is the provider for the datastore openstack-keystone? (even though i mention in the conf settings that it should use openstack-swift)
 `[ERROR] Command not considered safe to retry because request method is POST: [method=org.jclouds.openstack.keystone.v2_0.AuthenticationApi.public abstract org.jclouds.openstack.keystone.v2_0.domain.Access org.jclouds.openstack.keystone.v2_0.AuthenticationApi.authenticateWithTenantNameAndCredentials(java.lang.String,org.jclouds.openstack.keystone.v2_0.domain.PasswordCredentials`

**Comment by SentinelDataHub** [comment]
Dear @mwabakangwa,
1. Could you please perform a cURL manually to get Openstack token and verify that the connection between the machine and Openstack service is established?
2. Could you please clarify which version of jcloud are you using?
3. Moreover, did you configure the parameter “url” in the datastore ?
Here an example:     
`<ds:url>https://keystone9915.openstack.ovh.net:35358/v2.0</ds:url>`  

If you still encounter problems please don't hesitate to send us the dhus.xml file.
Regards,
DataHubSystem Team

**Comment by mwabakangwa** [comment]
@SentinelDataHub  Thank you for your response.

1. Yes the connection works with curl, i use this and it returns the token
curl -v -H  "X-Auth-User:tenantname:username" -H  "X-Auth-Key:key"  https://xxxxxxxxxx/auth
After that i am able to then list the containers and create, delete and get info about the containers with the generated token.
curl -i -H "X-Auth-Token: token" <url> -X GET  https://xxxxxxxxxx/auth
The connection also works when i use python-swiftclient.

2. Im using jclouds 1.9.2 

3. In the conf dhux.xml yes i do configure the datastore url, just like the example on step 4, on page 17 in the dhus admin manual.

I also tried to use the object storage url https://xxxxxxxxxx/v1 but this also did not work.

**Comment by SentinelDataHub** [comment]
Dear @mwabakangwa ,
Ceph is another provider as Openstack, but is not supported by the jclouds library.
Swift API are same, here the issue is the authentication part, Ceph uses a LDAP service yet Openstack uses keystone service for user authentication. Which explains these errors.
We kindly invite you to adopt openstack for using jclouds components.

Best Regards
SentinelDataHub Team
