### ISSUE TITLE
AJS GUI upload product problem

### ISSUE THREAD

**Issue by researcher1212** [SentinelDataHub/dhus-distribution#3]
Good day!

In AJS GUI / Upload Management tried to upload product S2A_MSIL1C_20160116T085312_N0201_R107_T36UUA_20160116T085621.zip

Got message: "Product Upload Succeeded "The file was created successfully.""

But product didn't appear at "Collections Management".

(DHuS deployment mode: single instance)

In dhus.log there is error :
[1.0.1-15-osf][2018-12-19 11:11:37,374][INFO ] Store product S2A_MSIL1C_20160116T085312_N0201_R107_T36UUA_20160116T085621 into datastores. (Ingester.java:104 - taskExecutor-3)
[1.0.1-15-osf][2018-12-19 11:11:37,375][WARN ] Unrecoverable error happen during ingestion of null (removing from database) (Ingester.java:160 - taskExecutor-3)
java.lang.NullPointerException
    at fr.gael.dhus.datastore.Ingester.ingest(Ingester.java:116)
….

In  hsqldb.log new record created and deleted at one time:
/*C1115*/SET SCHEMA PUBLIC
INSERT INTO PRODUCTS VALUES(10,'2018-12-19 11:11:36.934000','2018-12-19 11:11:36.931000',NULL,NULL,NULL,FALSE,NULL,'file:/home/dhus/local_dhus/tempos/S2A_MSIL1C_20160116T085312_N0201_R107_T36UUA_20160116T085621.zip',FALSE,NULL,'83b41c2a-30e1-409f-a5bc-c3f8eb93aadd',NULL,NULL,-1,'application/octet-stream',NULL,NULL,NULL,NULL,NULL,NULL,'7ca663b0-18fd-45f4-b324-c3dec64a2db4')
INSERT INTO PRODUCT_USER_AUTH VALUES(10,'7ca663b0-18fd-45f4-b324-c3dec64a2db4')
COMMIT
/*C1116*/SET SCHEMA PUBLIC
DELETE FROM PRODUCT_USER_AUTH WHERE PRODUCTS_ID=10 AND USERS_UUID='7ca663b0-18fd-45f4-b324-c3dec64a2db4'
DELETE FROM PRODUCTS WHERE ID=10
COMMIT

What may cause such error?

P.s. sorry for my English

[dhus.log](https://github.com/SentinelDataHub/dhus-distribution/files/2694692/dhus.log)
[hsqldb.log](https://github.com/SentinelDataHub/dhus-distribution/files/2694693/hsqldb.log)
[dhus(xml).txt](https://github.com/SentinelDataHub/dhus-distribution/files/2694703/dhus.xml.txt)

**Comment by SentinelDataHub** [comment]
Hi,
Thank you for your interest in our Project!
Sentinel DataHub System Team will support you very soon.

Cheers
