### ISSUE TITLE
Where is the description.xml 

### ISSUE THREAD

**Issue by alunacob** [SentinelDataHub/dhus-distribution#5]
As far as I am aware, an opensearch endpoint must serve the description.xml files with application/opensearchdescription+xml MIME type. 

How/Where can I get it?

**Comment by SentinelDataHub** [comment]
Hi @alunacob ,
Thank you for your interest in Our Project.
Please you can find further details here [How to use Open Search to discover products in the Data Hub archive](https://scihub.copernicus.eu/userguide/OpenSearchAPI).

The following URI returns an XML file including the list of the nodes of every products stored in the Data Hub archive.    
https://scihub.copernicus.eu/dhus/search?q=* 

Cheers
Sentinel DataHub System Team

**Comment by alunacob** [comment]
I  know how to use it and I know there are a lot of ad-hoc clients developed to consume sentinel data, but what I am aiming is for a generic Macihne-to-Machine (M2M) communication. By exposing the description.xml document, the endpoint is describing the search engine itself, so that any client application can use it.

Following the description.xml document, an opensearch client should be able to query the endpoint without needing to read any documentation, just following the specification.

**Comment by SentinelDataHub** [comment]
Hi @alunacob,
Please you can find the file openseach-description.xml at the following path: 
dhus-distribution/etc/opensearch-description-file.xml 
Cheers
