### ISSUE TITLE
How can I download time series data from Sentinel 5P?

### ISSUE THREAD

**Issue by MirelSIG** [SentinelDataHub/dhus-distribution#7]
I am designing a research for master thesis and I need to download the Sentinel 5P time series of a calendar year. Can someone help me please? It is very difficult to download the images of a year individually

**Comment by valgur** [comment]
You might find [`sentinelsat`](https://github.com/sentinelsat/sentinelsat) helpful here.
For example, to download all S5P products over a region for the past year you can do:
```
sentinelsat -u <user> -p <password> -g <aoi.geojson> --sentinel 5 --start NOW-1YEAR
```

**Comment by MirelSIG** [comment]
Thank you valgur...
I began with your script and generated another:
sentinelsat.exe -u s5pguest -p s5pguest -g tstmirel2.geojson.txt --sentinel 5 -s 20191012 -e 20191013 --url "https://s5phub.copernicus.eu/dhus" --producttype L2__NO2___
I need to clasify by contaminants
